### ISSUE TITLE
Adicionar página com publicações

### ISSUE THREAD

**Issue by fmarquesfilho** [coopera/coopera.github.io#6]
Exemplo: http://cradl.ics.uci.edu/?page_id=9

Tem que ser fácil de atualizar no Jekyll.

**Comment by fmarquesfilho** [comment]
@bernardogfilho você pode ajudar com essa issue?

**Comment by bernardogfilho** [comment]
Sim, foi mal a demora. Ainda hoje eu coloco no ar.

**Comment by bernardogfilho** [comment]
O arquivo em app/_data/publications.yml será usado para popular a página das publicações. Foi a maneira mais fácil que encontrei pra atualizar as publicações.

Ela segue um estilo bem simples, exemplo:

```yml
- year: 2011
  works:
    - autores... título do trabalho.
    - autores... título do trabalho

- year: 2010
  works:
    - autores... título do trabalho.
    - autores... título do trabalho
```
